<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!DOCTYPE pesonas [
    <!ELEMENT pesonas (datospersonales+, datoslaborales)>
    <!ELEMENT datospersonales (nombre,apellido,direccion,telefono,email*,foto,pie)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellido (#PCDATA)>
    <!ELEMENT direccion (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT email (#PCDATA)>
    <!ELEMENT foto EMPTY>
    <!ELEMENT pie (#PCDATA)>
    <!ELEMENT datoslaborales (empresa,direccion,cp)>
    <!ELEMENT empresa (#PCDATA)>
    <!ELEMENT cp (#PCDATA)>

    <!ATTLIST datospersonales edad CDATA #FIXED "18">
    <!ATTLIST foto src CDATA "./nodisponible.jpg">

    <!ENTITY copyright "@Fernando">
    <!ENTITY anyo "2022">
]>
<pesonas>
    <datospersonales>
        <nombre>Pedro</nombre>
        <apellido>Ramírez</apellido>
        <direccion>Calle ancha</direccion>
        <telefono>666666666</telefono>
        <email>yo@dflgñ.com</email>
        <email>yo@dflgñ.com</email>
        <foto src=""/>
        <pie>&copyright; &anyo;</pie>
    </datospersonales>
    <datospersonales edad="18">
        <nombre>Pedro</nombre>
        <apellido>Ramírez</apellido>
        <direccion>Calle ancha</direccion>
        <telefono>666666666</telefono>
        <email>yo@dflgñ.com</email>
        <foto src=""/>
        <pie>&copyright; &anyo;</pie>
    </datospersonales>
    <datoslaborales>
        <empresa>Empresa S.A</empresa>
        <direccion>CCC</direccion>
        <cp>41008</cp>
    </datoslaborales>
</pesonas>
