=== ADAME98/Exercise_LM_2T/XML ejemplo/XMLEJERCICIOS/ejercicio37.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="personas">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="persona" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"></xs:element>
                            <xs:element name="apellidos" type="xs:string"></xs:element>
                            <xs:element name="telefono">

                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:simpleType name="telefono">
        <xs:restriction base="xs:positiveInteger">
            <xs:pattern value="[0-9]{9}"></xs:pattern>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== ADAME98/Exercise_LM_2T/XML ejemplo/XMLEJERCICIOS/ejercicio37.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio37.xsd">
    <persona>
        <nombre>Juan</nombre>
        <apellidos>García</apellidos>
        <telefono>924555555</telefono>
    </persona>
    <persona>
        <nombre>Juan</nombre>
        <apellidos>García</apellidos>
        <telefono>924555555</telefono>
    </persona>
</personas>
